spring:
  application:
    name: flashcard-set-service
    localhost: localhost
  config:
    activate:
      on-profile: prod
  cloud:
    host:
      name: localhost
  data:
    redis:
      repositories:
        enabled: true
      host: localhost
      port: '6379'
      database: '1'
      timeout: '60000'
server:
  port: '9677'
logging:
  level:
    web: DEBUG
#spring:
#  datasource:
#    hikari:
#      connection-timeout: '60000'
#      maximum-pool-size: '5'
#server:
#  servlet:
#    session:
#      cookie:
#        http-only: true
#        secure: false
