spring:
  application:
    name: flashcard-service
    localhost: localhost
  config:
    activate:
      on-profile: dev
  cloud:
    host:
      name: localhost
  data:
    redis:
      repositories:
        enabled: true
      host: localhost
      port: '6379'
      database: '2'
      timeout: '60000'
server:
  port: '9678'
logging:
  level:
    web: DEBUG
#spring:
#  security:
#    user:
#      name: user
#      password: '1234'
#      roles: admin
#    filter:
#      dispatcher-types: async
#  datasource:
#    hikari:
#      connection-timeout: '60000'
#      maximum-pool-size: '5'
#server:
#  servlet:
#    session:
#      cookie:
#        http-only: true
#        secure: true
