spring:
  application:
    name: flashcards-gateway
    localhost: localhost
  cloud:
    host:
      name: localhost
  config:
    activate:
      on-profile: dev
server:
  port: '9676'
local:
  server:
    hostname: localhost
flashcardSet:
  uri: flashcardset-service
  host: localhost
  port: '9677'
  path:
    root: /flashcard-sets
    getAll: /get-all
    name: /get-by-name
    getById: /get-by-id
    create: /create-this-flashcard-set
    update: /update-this-flashcard-set
    delete: /delete-this-flashcard-set
    deleteById: /delete-flashcard-set-by-id
flashcard:
  uri: flashcard-service
  host: localhost
  port: '9678'
  path:
    root: /flashcards
    getAll: /get-all
    name: /get-by-name
    getById: /get-by-id
    getByIds: /get-by-ids
    exists: /exists-by-id
    getByFlashcardSetId: /get-by-flashcard-set-id
    save: /save-flashcard
    saveCards: /save-flashcards
    update: /update-flashcard
    delete: /delete-flashcard
    deleteById: /delete-flashcard-by-id
    deleteThese: /delete-these-flashcards
    deleteTheseIds: /delete-these-flashcards-by-ids
    deleteByName: /delete-flashcard-by-name

#okta:
#  oauth2:
#    issuer: '""'
logging:
  level:
    web: DEBUG
#  file:
#    name: flashcards-gateway.log
#    max-size: 5MB
#    max-history: '10'
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n'
